name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # 🎀 JAV Lib Manager Feature Request

        Thanks for sharing your idea! Please fill out the form below to help us understand your suggestion.

        ---
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem are you facing?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds?
